### ISSUE TITLE
Importing Dash.jl component libraries prior to Dash throws a "UndefVarError: DashBase not defined" error

### ISSUE THREAD

**Issue by rpkyle** [plotly/dash#1432]
While generating the Julia version of `DashUserGuideComponents`, I noticed that the `Project.toml` doesn't contain an entry for `DashBase`, e.g.

```toml
name = "DashUserGuideComponents"
uuid = "1b08a953-4be3-4667-9a23-e667f8ac7b1d"
authors = ["Chris P <chris@plotly.com>"]
version = "0.0.4"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1"
```

Glancing at `DashCoreComponents`, it looks like the `Project.toml` includes an entry for `DashBase` in both the `[deps]` and `[compat]` sections.

@waralex @alexcjohnson
