### ISSUE TITLE
[BUG] Upload component styling using HTML classes

### ISSUE THREAD

**Issue by jburtscher** [plotly/dash#3246]
As far as I can tell, the `className_*` properties in the upload component don't seem to have any effect (I'm using Dash 3.0.1 on Windows with Edge Version 134.0.3124.83).  
With the following app and CSS file, the upload component is colored yellow but does not change color when I drag files onto it (be it one file for the active case or multiple files for the rejected case):

```python
from dash import Dash, dcc

app = Dash()
app.layout = dcc.Upload(
    "Upload",
    className="upload",
    className_active="upload-active",
    className_reject="upload-reject",
)
app.run(debug=True)
```

```css
.upload { background: yellow; }
.upload-active { background: green; }
.upload-reject { background: red; }
```

If I use the `style_*` properties, everything works fine:

```python
from dash import Dash, dcc

app = Dash()
app.layout = dcc.Upload(
    "Upload",
    style={"background": "yellow"},
    style_active={"background": "green"},
    style_reject={"background": "red"},
)
app.run(debug=True)
```
