### ISSUE TITLE
Install from Anaconda 

### ISSUE THREAD

**Issue by elchinot7** [plotly/dash#79]
Hi guys, 

I'm just wondering if you have or are planning an official Dash version for Anaconda installations. 

I need to say that Dash is simple awesome. Thanks for this library.

Cheers

**Comment by chriddyp** [comment]
Thanks @elchinot7 ! 

Yeah, we could add a `conda` version. It _is_ possible to install packages from `pip` into a `conda` environment, right? What are the benefits of having the package in both repositories?

**Comment by elchinot7** [comment]
@chriddyp  you are right, in regular situation it is posible to install any package using `pip`, however in some situations, in azure Machine Learning Studio for example, only conda versions are accesible.

**Comment by rpanai** [comment]
@elchinot7 It is possible but, as example, if you are using pandas from conda it reinstalls on top one with pip. Which is not very elegant. A plotly is available on conda it will be great to have dash too.

**Comment by jtpio** [comment]
With conda it's possible to define an environment.yml file:
```yaml
name: dash-conda-example
dependencies:
  - python=3
  - pip
  - numpy
  - pip:
    - dash==0.20.0
    - dash-renderer==0.11.2
    - dash-html-components==0.8.0
    - dash-core-components==0.18.1
```

And run: `conda env create` to create the conda environment and install all the dependencies at once.
